{{- if .Values.secrets.autogenerate }}

{{- $keycloakNamespace := .Values.keycloak.namespace -}}
{{- $platformNamespace := .Release.Namespace -}}

{{-
/*
Existing Secret lookups.
lookup returns Secret.data values already base64-encoded.
*/
-}}

{{/*Keycloak namespace*/}}

{{- $keycloakSecretName := .Values.keycloak.configuration.adminSecret.name -}}
{{- $keycloakSecret := (lookup "v1" "Secret" $keycloakNamespace $keycloakSecretName | default dict) -}}
{{- $keycloakSecretData := (get $keycloakSecret "data" | default dict) -}}

{{- $keycloakGraphModelingSecretName := .Values.keycloak.configuration.graphModelingSecret.name -}}
{{- $keycloakGraphModelingSecret := (lookup "v1" "Secret" $keycloakNamespace $keycloakGraphModelingSecretName | default dict) -}}
{{- $keycloakGraphModelingSecretData := (get $keycloakGraphModelingSecret "data" | default dict) -}}

{{/*Platform namespace*/}}

{{- $keycloakProvisioningAdminSecretName := .Values.keycloak_provision.keycloakCredentials.secretName -}}
{{- $keycloakProvisioningAdminSecret := (lookup "v1" "Secret" $keycloakNamespace $keycloakSecretName | default dict) -}}
{{- $keycloakProvisioningAdminSecretData := (get $keycloakSecret "data" | default dict) -}}

{{- $graphModelingSecretName := (index .Values "graph-modeling").configuration.propertiesOverrides.existingSecret -}}
{{- $graphModelingSecret := (lookup "v1" "Secret" $platformNamespace $graphModelingSecretName | default dict) -}}
{{- $graphModelingSecretData := (get $graphModelingSecret "data" | default dict) -}}

{{- $graphModelingAdminCredentialsSecretName := .Values.secrets.graphModeling.adminCredentialsSecretName -}}
{{- $graphModelingAdminCredentialsSecret := (lookup "v1" "Secret" $platformNamespace $graphModelingAdminCredentialsSecretName | default dict) -}}
{{- $graphModelingAdminCredentialsSecretData := (get $graphModelingAdminCredentialsSecret "data" | default dict) -}}

{{- $graphdbInitialUsersSecretName := .Values.graphdb.security.initialUsers.existingSecret -}}
{{- $graphdbInitialUsersSecret := (lookup "v1" "Secret" $platformNamespace $graphdbInitialUsersSecretName | default dict) -}}
{{- $graphdbInitialUsersSecretData := (get $graphdbInitialUsersSecret "data" | default dict) -}}

{{- $graphdbAdminCredentialsSecretName := .Values.secrets.graphdb.adminCredentialsSecretName -}}
{{- $graphdbAdminCredentialsSecret := (lookup "v1" "Secret" $platformNamespace $graphdbAdminCredentialsSecretName | default dict) -}}
{{- $graphdbAdminCredentialsSecretData := (get $graphdbAdminCredentialsSecret "data" | default dict) -}}

{{- $graphdbProvisionerCredentialsSecretName := .Values.secrets.graphdb.provisionerCredentialsSecretName -}}
{{- $graphdbProvisionerCredentialsSecret := (lookup "v1" "Secret" $platformNamespace $graphdbProvisionerCredentialsSecretName | default dict) -}}
{{- $graphdbProvisionerCredentialsSecretData := (get $graphdbProvisionerCredentialsSecret "data" | default dict) -}}

{{- $graphdbProvisionerTokenSecretName := .Values.graphdb.security.provisioner.existingSecret -}}
{{- $graphdbProvisionerTokenSecret := (lookup "v1" "Secret" $platformNamespace $graphdbProvisionerTokenSecretName | default dict) -}}
{{- $graphdbProvisionerTokenSecretData := (get $graphdbProvisionerTokenSecret "data" | default dict) -}}

{{- $graphdbClusterTokenSecretName := .Values.graphdb.cluster.token.existingSecret -}}
{{- $graphdbClusterTokenSecret := (lookup "v1" "Secret" $platformNamespace $graphdbClusterTokenSecretName | default dict) -}}
{{- $graphdbClusterTokenSecretData := (get $graphdbClusterTokenSecret "data" | default dict) -}}

{{-
/*
Calculate or reuse Keycloak secret values
*/
-}}

{{- $keycloakAdminPasswordB64 := coalesce
      (get $keycloakSecretData "KEYCLOAK_ADMIN_PASSWORD")
      (get $graphModelingSecretData "POOLPARTY_KEYCLOAK_ADMIN_PASSWORD")
      (randAlphaNum 24 | b64enc)
-}}

{{- $keycloakProvisioningAdminPasswordB64 := coalesce
      (get $keycloakProvisioningAdminSecretData "KEYCLOAK_ADMIN_PASSWORD")
      $keycloakAdminPasswordB64
-}}

{{- $keycloakLoginClientSecretB64 := coalesce
      (get $keycloakGraphModelingSecretData "POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET")
      (get $graphModelingSecretData "POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphModelingSuperAdminPasswordB64 := coalesce
      (get $keycloakGraphModelingSecretData "POOLPARTY_SUPER_ADMIN_PASSWORD")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphModelingEncryptionPasswordB64 := coalesce
      (get $graphModelingSecretData "_POOLPARTY_ENCRYPTION_PASSWORD")
      (randAlphaNum 24 | b64enc)
-}}

{{-
/*
Calculate or reuse GraphDB secret values
*/
-}}

{{- $graphdbAdminPasswordB64 := coalesce
      (get $graphdbAdminCredentialsSecretData "password")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphdbProvisionerPasswordB64 := coalesce
      (get $graphdbProvisionerCredentialsSecretData "password")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphdbAdminPassword := ($graphdbAdminPasswordB64 | b64dec) -}}
{{- $graphdbProvisionerPassword := ($graphdbProvisionerPasswordB64 | b64dec) -}}

{{- $graphdbAdminPasswordHash := regexReplaceAll "^admin:" (htpasswd "admin" $graphdbAdminPassword) "" -}}
{{- $graphdbProvisionerPasswordHash := regexReplaceAll "^provisioner:" (htpasswd "provisioner" $graphdbProvisionerPassword) "" -}}

{{- $graphdbProvisionerToken := printf "provisioner:%s" $graphdbProvisionerPassword | b64enc -}}
{{- $graphdbProvisionerTokenB64 := $graphdbProvisionerToken | b64enc -}}

{{- $graphdbClusterTokenB64 := coalesce
      (get $graphdbClusterTokenSecretData "GRAPHDB_CLUSTER_TOKEN")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphdbUsersJson := printf `{
  "users": {
    "admin": {
      "username": "admin",
      "password": "{bcrypt}%s",
      "grantedAuthorities": [ "ROLE_ADMIN" ],
      "appSettings": {
        "DEFAULT_INFERENCE": true,
        "DEFAULT_VIS_GRAPH_SCHEMA": true,
        "DEFAULT_SAMEAS": true,
        "IGNORE_SHARED_QUERIES": false,
        "EXECUTE_COUNT": true
      },
      "dateCreated": 1618403171751
    },
    "provisioner": {
      "username": "provisioner",
      "password": "{bcrypt}%s",
      "grantedAuthorities": [ "ROLE_ADMIN" ],
      "appSettings": {
        "DEFAULT_INFERENCE": true,
        "DEFAULT_VIS_GRAPH_SCHEMA": true,
        "DEFAULT_SAMEAS": true,
        "IGNORE_SHARED_QUERIES": false,
        "EXECUTE_COUNT": true
      },
      "dateCreated": 1618403171751
    }
  }
}
` $graphdbAdminPasswordHash $graphdbProvisionerPasswordHash -}}

{{- $graphdbUsersJsB64 := coalesce
      (get $graphdbInitialUsersSecretData "users.js")
      ($graphdbUsersJson | b64enc)
-}}

{{-
/*
Create/update secrets
*/
-}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $keycloakSecretName }}
  namespace: {{ $keycloakNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ "admin" | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $keycloakAdminPasswordB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $keycloakGraphModelingSecretName }}
  namespace: {{ $keycloakNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  POOLPARTY_SUPER_ADMIN_PASSWORD: {{ $graphModelingSuperAdminPasswordB64 | quote }}
  POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET: {{ $keycloakLoginClientSecretB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $keycloakSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ "admin" | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $keycloakProvisioningAdminPasswordB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphModelingSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  _POOLPARTY_ENCRYPTION_PASSWORD: {{ $graphModelingEncryptionPasswordB64 | quote }}
  POOLPARTY_KEYCLOAK_ADMIN_USERNAME: {{ "admin" | b64enc | quote }}
  POOLPARTY_KEYCLOAK_ADMIN_PASSWORD: {{ $keycloakAdminPasswordB64 | quote }}
  POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET: {{ $keycloakLoginClientSecretB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphdbInitialUsersSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  users.js: {{ $graphdbUsersJsB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphdbAdminCredentialsSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $graphdbAdminPasswordB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphdbProvisionerCredentialsSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  username: {{ "provisioner" | b64enc | quote }}
  password: {{ $graphdbProvisionerPasswordB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphdbProvisionerTokenSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  GRAPHDB_AUTH_TOKEN: {{ $graphdbProvisionerTokenB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphdbClusterTokenSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  GRAPHDB_CLUSTER_TOKEN: {{ $graphdbClusterTokenB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphModelingAdminCredentialsSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  username: {{ "superadmin" | b64enc | quote }}
  password: {{ $graphModelingSuperAdminPasswordB64 | quote }}

{{- if .Values.graphrag.enabled }}

{{- $graphragConversationDatabaseCredentialsSecretName := .Values.secrets.graphrag.conversation.databaseCredentialsSecretName -}}
{{- $graphragConversationDatabaseCredentialsSecret := (lookup "v1" "Secret" $keycloakNamespace $keycloakSecretName | default dict) -}}
{{- $graphragConversationDatabaseCredentialsSecretData := (get $keycloakSecret "data" | default dict) -}}

{{- $graphragConversationKeycloakSecretsSecretName := .Values.secrets.graphrag.conversation.keycloakSecretsSecretName -}}
{{- $graphragConversationKeycloakSecretsSecret := (lookup "v1" "Secret" $keycloakNamespace $keycloakSecretName | default dict) -}}
{{- $graphragConversationKeycloakSecretsSecretData := (get $keycloakSecret "data" | default dict) -}}

{{- $graphragWorkflowsEncryptionSecretName := .Values.secrets.graphrag.workflows.encryptionSecretName -}}
{{- $graphragWorkflowsEncryptionSecret := (lookup "v1" "Secret" $keycloakNamespace $keycloakSecretName | default dict) -}}
{{- $graphragWorkflowsEncryptionSecretData := (get $keycloakSecret "data" | default dict) -}}

{{- $graphragConversationDatabasePasswordB64 := coalesce
      (get $graphragConversationDatabaseCredentialsSecretData "password")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphragConversationKeycloakClientSecretB64 := coalesce
      (get $graphragConversationKeycloakSecretsSecretData "client-secret")
      (randAlphaNum 24 | b64enc)
-}}

{{- $graphragWorkflowsEncryptionSecretB64 := coalesce
      (get $graphragWorkflowsEncryptionSecretData "N8N_ENCRYPTION_KEY")
      (randAlphaNum 24 | b64enc)
-}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphragConversationDatabaseCredentialsSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  username: {{ "graphrag" | b64enc | quote }}
  password: {{ $graphragConversationDatabasePasswordB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphragConversationKeycloakSecretsSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  client-secret: {{ $graphragConversationKeycloakClientSecretB64 | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $graphragConversationKeycloakSecretsSecretName }}
  namespace: {{ $platformNamespace }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.preserve }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
type: Opaque
data:
  N8N_ENCRYPTION_KEY: {{ $graphragWorkflowsEncryptionSecretB64 | quote }}
{{- end }}
{{- end }}
