{{- if and .Values.keycloak.enabled .Values.keycloak_provision.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphwise-platform.keycloak-provision.scripts.configmap.name" . }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- with .Values.keycloak_provision.configmap.annotations }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
data:
  keycloak-utils.sh: |-
    {{- tpl (.Files.Get "files/keycloak/keycloak-utils.sh" | trim) . | nindent 4 }}
{{- end }}
