{{- if and .Values.elasticsearch.enabled .Values.elasticsearch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ coalesce .Values.elasticsearch.serviceAccount.name .Values.elasticsearch.name }}
  labels:
    {{- include "graphwise-platform.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.elasticsearch.serviceAccount.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
